server:
  port: 8084
spring:
  application:
    name: MessagingService
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:18375
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:49152/infiniteChat?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: gK3T9n%q2M@j7Z4
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      initialization-fail-timeout: 10000
      idle-timeout: 30000
      max-lifetime: 60000
      connection-timeout: 30000
      validation-timeout: 3000
      connection-test-query: SELECT 1
      pool-name: HikariCP
  redis:
    host: localhost
    database: 0
    port: 59000
    password: e65K4t8w2
    # 配置 Redis 连接池
    lettuce:
      pool:
        min-idle: 4
        max-idle: 8
        max-active: 8
        max-wait: -1ms
