server:
  port: 10010

spring:
  application:
    name: GateWay
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:18375
    gateway:
      httpclient:
        connect-timeout: 60000  #连接超时时间,单位毫秒
        response-timeout: 60000 #响应超时时间,单位毫秒
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:10010"
            allowedMethods:
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
              - "PATCH"
              - "OPTIONS"
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 36000
      routes:
#        - id: after_route
#          uri: https://www.qq.com/
#          predicates:
#          - After=2025-01-20T17:42:47.789-07:00[America/Denver]
#        - id: cookie_route
#          uri: http://117.72.206.69/
#          predicates:
#            - Cookie=chocolate, ch.p
        # 登录认证服务
        - id: AuthenticationService
          uri: lb://AuthenticationService
          predicates:
            - Path=/api/v1/user/**
          filters:
            - AddRequestHeader=X-Request-Source, InfiniteChat-GateWay
            - AddResponseHeader=X-Response-Source, InfiniteChat-GateWay
        # 实时通讯服务
        - id: RealTimeCommunicationService
          uri: lb://RealTimeCommunicationService
          predicates:
            - Path=/api/v1/message/**
            - Path=/api/v1/chat/**
        # Netty 长链接服务
        - id: NettyServer
          uri: lb:ws://NettyServer
          predicates:
            - Path=/api/v1/netty
        # 离线存储模块
        - id: OfflineDataStoreService
          uri: lb://OfflineDataStoreService
          predicates:
            - Path=/api/v1/offline/**
        # 消息模块
        - id: MessagingService
          uri: lb://MessagingService
          predicates:
            - Path=/api/v1/chat/**

